# Generated by Django 5.1.6 on 2025-02-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sunlight', models.CharField(max_length=50)),
                ('water_needs', models.CharField(max_length=50)),
                ('planting_season', models.CharField(max_length=50)),
            ],
        ),
    ]
